
development:
  adapter: postgresql
  encoding: unicode
  database: rr_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rr_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rr_production
  pool: 5
  username:
  password:
